/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.comtec.log_roller;

import com.comtec.log_roller.component.FileHandler;

public class App {

    public static void main(String[] args) {
        FileHandler handler = FileHandler.getInstance();

        handler.copyFile();
        handler.deleteFile();
    }
}
